# This file records information about this repo. Its use is described in OEP-55:
# https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'xblock-skill-tagging'
  description: "Django app plugin for fetching and verifying tags for xblock skills."
  annotations:
    # (Optional) Annotation keys and values can be whatever you want.
    # We use it in Open edX repos to have a comma-separated list of GitHub user
    # names that might be interested in changes to the architecture of this
    # component.
    openedx.org/arch-interest-groups: ""
    openedx.org/release: "main"
spec:
  owner: group:2u-xblockskilltagging-maintainers
  type: 'library'
  lifecycle: 'production'
  dependsOn:
  - 'edx-platform'
  - 'taxonomy-connector'
